PACKAGE_NAME="rmi4-psiopi"
PACKAGE_VERSION="1.1"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
BUILT_MODULE_NAME[0]="rmi_core"
DEST_MODULE_LOCATION[0]="/updates/dkms"
BUILT_MODULE_NAME[1]="rmi_i2c"
DEST_MODULE_LOCATION[1]="/updates/dkms"
AUTOINSTALL="yes"
# The sources are from 6.12 and use newer kernel APIs
BUILD_EXCLUSIVE_KERNEL="^(6\.(1[2-9]|[2-9][0-9])|[7-9]\.)"
